@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CoursePilotParser" as CoursePilotParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> CoursePilotParser : parseCommand(undo)
activate CoursePilotParser

create UndoCommand
CoursePilotParser -> UndoCommand
activate UndoCommand

UndoCommand --> CoursePilotParser
deactivate UndoCommand

CoursePilotParser --> LogicManager : u
deactivate CoursePilotParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoCoursePilot()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
