@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCoursePilot" as VersionedCoursePilot MODEL_COLOR
end box

[-> Model : undoCoursePilot()
activate Model

Model -> VersionedCoursePilot : undo()
activate VersionedCoursePilot

VersionedCoursePilot -> VersionedCoursePilot :resetData(ReadOnlyCoursePilot)
VersionedCoursePilot --> Model :
deactivate VersionedCoursePilot

[<-- Model
deactivate Model

@enduml
